#!/bin/bash -l
# Name your job (used in the PBS output file names)
#PBS -N GPU_chatbot_test

# Specify the gpuq queue
#PBS -q gpuq

# Specify the number of gpus
#PBS -l nodes=1:ppn=2
#PBS -l gpus=1

# Specify the gpu feature
#PBS -l feature=gpu

# Specify your resource account (use qr command to determine)
#PBS -A f002bw

# Specify how much time you think the job will run
#PBS -l walltime=00:01:00

# mail is sent to you when the job starts and when it terminates or aborts
#PBS -M jason.m.kim.gr@dartmouth.edu
#PBS -m bea

# Join error and standard output into one file
#PBS -j oe

source activate hpc_chatbot

# Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR

# Parse the PBS_GPUFILE to determine which GPU you have been assigned
# and unset CUDA_VISIBLE_DEVICES
gpuNum=`cat $PBS_GPUFILE | sed -e 's/.*-gpu//g'`
unset CUDA_VISIBLE_DEVICES
# if using PyCUDA set the CUDA_DEVICE environment variable
export CUDA_DEVICE=$gpuNum
# Pass the GPU number as an argument to your program
python3 torchtest.py > testoutput.txt
exit 0